apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower-shop-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flower-shop-api-gateway
  template:
    metadata:
      labels:
        app: flower-shop-api-gateway
    spec:
      containers:
        - name: api-gateway
          image: nginx:alpine
          ports:
            - containerPort: 80
